### PR TITLE
Read binary files successfully with binread

### PR DESCRIPTION
**Pull request by Christoph-D**
File.read does not work with binary files correctly, but IO.binread does.

### CODE REVIEW

**Comment by adrienthebo** [comment]
This will make binary files be read as ASCII_8BIT, but it'll break any existing use of this backend that relies on UTF-8 encoded strings.

Take the following example:

```yaml
# common.d/utf-8
username_prefix: "foo :username:"

```puppet
$template_value = hiera("template_value")
# $template_value will have the ASCII-8BIT character encoding
$username = "Erik Dalén"
# $username will have the UTF-8 encoding and has UTF-8 characters, which means that
# it can't be intermixed with $template_value
$final_value = regsubst($template_value, ":username:", $username)
```

Merging this change would cause Puppet to raise an exception because this would try to do a regex substitution between a binary string and a UTF-8 string, which will break in Ruby 1.9 and greater.

I've added tests at https://github.com/adrienthebo/hiera-file/pull/16 to exercise some of the character encoding issues.

One option could be to add an option for whether data should be read as binary or not, based on a feature flag like the `:interpolate` feature: https://github.com/adrienthebo/hiera-file/commit/452247ddc80a44e8eeb56bc68d06fde472609490 .

As it stands this cannot be merged; if you can change this to maintain compatibility with existing users and preserve string encodings I would consider merging it.

**Comment by carlp101** [comment]
The ability to work with binary files would be very useful. I'd like to be able to use the following code to define a resource so I can retrieve a binary file and place it in a chosen location:

    define system::loadfile::template (
      $target_file,
      $file_content,
      $owner,
      $group,
      $mode,
    ){
      file { "${target_file}":
        content => hiera("$file_content", undef),
        owner   => $owner,
        group   => $group,
        mode    => $mode,
      }
    }

**Comment by adrienthebo** [comment]
@carlp101 the comment on https://github.com/adrienthebo/hiera-file/pull/15#issuecomment-162656020 means that this still can't be merged; if you can solve that issue then we can merge this change in.

**Comment by bastelfreak** [comment]
Hi @Christoph-D, are you still interested in getting this merged? If so, could you please rebase against our latest master branch?

**Comment by Christoph-D** [comment]
Hi @bastelfreak, sorry, I have no intention to work on this pull request in the near future because (for unrelated reasons) I stopped using puppet.

I'll close this pull request because the issue in https://github.com/voxpupuli/hiera-file/pull/15#issuecomment-162656020 still stands: this feature needs backwards compatibility and cannot be merged in the current state even after a rebase.

**Pull request closed without merging**
