### PR TITLE
Updated URLs for TravisCI badge in REAMDE.md

### LINKED ISSUE #18: Fix Travis badge link

### PR DESCRIPTION
**Pull request by walerian777**
Resolves #18.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @walerian777, thanks for this PR. Could you drop ruby 1.9 and 1.8 from the testmatrix, and add 2.2 and 2.3 instead? If they work I can merge this.

**Comment by walerian777** [comment]
Done it in #21.

**Comment by bastelfreak** [comment]
Merged #21. Can you rebase this one?

**Comment by walerian777** [comment]
GitHub doesn't allow me to push to this PR (as you can see the scary `unknown repository`) below the PR title, so I am opening a new one - already rebased #22.

**Pull request closed without merging**
